name: DevOps Learning
on:
  push:
    branches:
      - s3
jobs:
  gh-pages-deploy:
    name: Build & Deploy VueJs
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - uses: actions/labeler@v2
          with:
            repo-token: ${{ secrets.DEVOPS }}
        - name: Install packages
          run: npm i
        - name: Build
          run: npm run build
        - name: Upload to S3
          run: |
            aws s3 rm s3://${{secrets.S3_BUCKET}} --recursive && aws s3 cp ./dist s3://${{secrets.S3_BUCKET}} --recursive
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}