name: DevOps Learning
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Build & Deploy VueJs
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '16'
        - uses: actions/labeler@v2
          with:
            repo-token: ${{ secrets.DEVOPS }}
        - name: Install packages
          run: npm i
        - name: Set Creds
          run: git config --global user.name "thanhinterpol" && git config --global user.email "thanhinterpol@gmail.com"
        # - name: Build
        #   run: npm run build
        - name: Deploy
          with:
            repository: thanhinterpol/vuejs_demo
            token: ${{ secrets.DEVOPS }}
          run: bash .github/workflows/deploy.sh